//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        public int ShoeID { get; set; }
        public string ShoeName { get; set; }
        public string ShoePhoto { get; set; }
        public string ShoeColor { get; set; }
        public string ShoeSeason { get; set; }
        public string ShoeOccasion { get; set; }
        public int ShoeTypeID { get; set; }
    
        public virtual ShoeType ShoeType { get; set; }
    }
}
